version: '3.8'
services:
  frontend:
    image: camlongtran/hom-nay-an-gi-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: homnay_frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
